export const Projectsdata = [
  {
    title: "Vital Ease ",
    about:
      "The Patient Management System, built with React, Next.js, and TypeScript, leverages ShadCN UI for design and Appwrite for backend services. Secure authentication is implemented with NextAuth. Users can create accounts, request appointments, update details, and receive SMS updates, while admins efficiently manage appointments and system stats",
    images: [
      "/vital/1.jpg",
      "/vital/2.jpg",
      "/vital/3.jpg",
      "/vital/4.jpg",
      "/vital/5.jpg",
      "/vital/6.jpg",
    ],
    featuresdata: [
      "Users can create accounts and provide detailed patient information via an extensive form.",
      "Users can request appointments and receive SMS updates on their status via Twilio.",
      "Users can update their information and upload receipt images for record-keeping.",
      "Admins can securely log in with OTP to access the dashboard.",
      "Admins can view system stats and manage appointment requests in a table format.",
      "Appointment requests can be canceled or scheduled by admins with notes or reasons.",
      "Receipt images can be uploaded and managed using React-Dropzone.",
      "The system is built with modern technologies like Next.js, ShadCN UI, TailwindCSS, and Appwrite.",
    ],
    link: "https://vital-ease-tawny.vercel.app/",
    code: "https://github.com/Shahmeer-09/Vital-Ease",
  },
  {
    title: "ShoeStop",
    about:
      "This e-commerce shoe store, built with Next.js, features an admin dashboard for managing sales, products, and promotions. Users can shop by category, enjoy a seamless checkout with Stripe, and secure authentication with Kinde Auth. Enhanced by ShadCN UI, Upstash Redis, and Prisma-backed NeonDB for optimal performance.",
    images: [
      "/shoe/2.jpg",
      "/shoe/1.jpg",
      "/shoe/3.jpg",
      "/shoe/4.jpg",
      "/shoe/5.jpg",
      "/shoe/6.jpg",
      "/shoe/7.jpg",
      "/shoe/8.jpg",
      "/shoe/9.jpg",
      "/shoe/10.jpg",
      "/shoe/11.jpg",
      "/shoe/12.jpg",
      "/shoe/13.jpg",
      "/shoe/14.jpg",
    ],
    featuresdata: [
      "Admin dashboard to analyze sales and user revenue using interactive charts.",
      "Create, edit, and delete products categorized by men, women, and kids.",
      "Easily publish or archive products to manage inventory.",
      "Manage banners and promotions directly from the dashboard.",
      "Shop by category and add products to the cart effortlessly.",
      "Seamless and secure checkout process integrated with Stripe.",
      "Fast and scalable frontend powered by Next.js.",
      "Amazing UI features designed with ShadCN UI.",
      "Secure user authentication using Kinde Auth.",
      "Optimized caching and performance with Upstash Redis and Neon(Postgres)DB using Prisma.",
    ],
    link: "https://nextjs-eccommerce-app.vercel.app/",
    code: "https://github.com/Shahmeer-09/NextjsEccommerce-app",
  },
  {
    title: "FoundersIO",
    about:
      "FoundersIO is a Next.js web app built with React and TypeScript, using Sanity for content management and NextAuth for secure GitHub authentication. MarkdownKit enables rich text formatting. Users can create, view, and manage business pitches via a landing page, create page, profile page, and detailed pitch views.",
    images: [
      "/founder/1.jpg",
      "/founder/2.jpg",
      "/founder/3.jpg",
      "/founder/4.jpg",
      "/founder/5.jpg",
      "/founder/6.jpg",
      "/founder/7.jpg",
      "/founder/8.jpg",
      "/founder/9.jpg",
    ],
    featuresdata: [
      "Users can sign up using their GitHub accounts via NextAuth for authentication.",
      "Create personalized business pitches that others can view and engage with.",
      "A landing page displays all pitches made by users for public viewing.",
      "A 'Create' page allows users to draft and publish new business pitches.",
      "A profile page lets users view, manage, and update all their pitches.",
      "Each pitch has a detailed view page with comprehensive pitch information.",
      "A 'Views' tag displays the total number of views for each pitch.",
      "Seamless integration of Next.js and TypeScript for a fast and scalable web app.",
      "TailwindCSS ensures a responsive and modern user interface.",
      "Sanity is used for managing and storing pitches as structured content.",
    ],
    link: "https://foundersio.vercel.app/",
    code: "https://github.com/Shahmeer-09/foundersio",
  },
  {
    title: "Jobify",
    about:
      "Jobify is job diary web app , built with React, Node.js, Express, and MongoDB, helps users manage job applications. With React Query for data fetching and React Router DOM for navigation, it features pages for stats, adding jobs, and profile management. The app includes a light/dark mode toggle and a user-friendly dashboard.",
    images: [
      "/job/1.jpg",
      "/job/2.jpg",
      "/job/3.jpg",
      "/job/4.jpg",
      "/job/5.jpg",
      "/job/6.jpg",
      "/job/7.jpg",
      "/job/8.jpg",
      "/job/9.jpg",
      "/job/10.jpg",
      "/job/11.jpg",
      "/job/12.jpg",
      "/job/13.jpg",
      "/job/14.jpg",
    ],

    featuresdata: [
      "Users can log in, sign up, or explore as a test user.",
      "A landing page lists all applied and pending job requests.",
      "A stats page displays visual insights into job applications.",
      "Users can add new jobs via an 'Add New Job' page.",
      "Profile page allows users to manage their account details.",
      "Admin page provides tools for managing the application process.",
      "Diary functionality to record and organize job applications by status.",
      "Light and dark mode toggle for personalized user experience.",
      "React Router DOM enables seamless navigation between pages.",
      "Built with React, Node.js, Express, MongoDB, and React Query for robust performance.",
    ],
    link: "https://job-find-mern.vercel.app/",
    code: "https://github.com/Shahmeer-09/JobFind-mern",
  },
  {
    title: "Sent",
    about:
      "Sent, is a real-time chat application developed using the MERN stack and pusher.js. It features user authentication, secure password reset, real-time messaging, group chat functionality, and a user-friendly interface and many more built with react.js and Tailwind CSS. Atom is used for efficient state management.",
    images: [
      "/sent/1.jpg",
      "/sent/2.jpg",
      "/sent/3.jpg",
      "/sent/4.jpg",
      "/sent/5.jpg",
      "/sent/6.jpg",
      "/sent/7.jpg",
      "/sent/8.jpg",
      "/sent/9.jpg",
      "/sent/10.jpg",
      "/sent/11.jpg",
      "/sent/12.jpg",
      "/sent/13.jpg",
      "/sent/14.jpg",
      "/sent/15.jpg",
      "/sent/16.jpg",
      "/sent/17.jpg",
    ],

    featuresdata: [
      "Log in and sign up for an account.",
      "Explore the application as a test user.",
      "View a list of all applied and pending job requests.",
      "Add new job applications with ease.",
      "Gain valuable insights into your job applications through a dedicated stats page.",
      "Update and manage your account details within the profile page.",
      "Access administrative tools for managing the application process (if applicable).",
      "Utilize the diary feature to record and organize job applications by status.",
      "Toggle between light and dark mode to suit your preference.",
      "Navigate effortlessly between pages using React Router DOM.",
      "Built with a combination of React, Node.js, Express, MongoDB, and React Query for optimal performance and reliability.",
    ],
    link: "https://sent-mocha.vercel.app/",
    code: "https://github.com/Shahmeer-09/sent",
  },
  {
    title: "Link up",
    about:
      "LinkUp is a chat application built with the MERN stack, Firebase Auth, and Socket.IO. It provides seamless registration, login, and real-time one-to-one chatting. Users can send and receive chat requests, exchange messages, emojis, images, and explore profiles in a user-friendly interface designed with Next-UI.",
    images:  [
      "/linkup/1.jpg",
      "/linkup/2.jpg",
      "/linkup/3.jpg",
      "/linkup/4.jpg",
      "/linkup/5.jpg",
      "/linkup/6.jpg",
      "/linkup/7.jpg",
      "/linkup/8.jpg",
      "/linkup/9.jpg",
      "/linkup/10.jpg",
      "/linkup/11.jpg",
      "/linkup/12.jpg",
    ],

    featuresdata:[
      "Users can register and log in securely with Firebase Auth.",
      "Change password functionality for account management.",
      "Send and receive chat requests in real-time.",
      "Approve or delete incoming chat requests from other users.",
      "One-to-one chat functionality for private conversations.",
      "Send images and emojis to make chats more engaging.",
      "View detailed profiles of other users.",
      "Real-time availability status of users for initiating chats.",
      "User-friendly interface built with Next-UI and React Hook Form.",
      "Built with MERN stack and Socket.IO for robust performance and scalability."
    ],
    link: "",
    code: "https://github.com/Shahmeer-09/Link",
  },
  {
    title: "Hash",
    about:
      "Hash is a MERN stack-based social platform, similar to Threads or Twitter. It allows users to create and interact with posts, follow/unfollow others, like, and comment. Users can manage their profiles, explore others' profiles, and enjoy light/dark modes in a responsive Chakra UI and Tailwind CSS design.",
    images:  [
      "/thread/1.jpg",
      "/thread/2.jpg",
      "/thread/3.jpg",
      "/thread/4.jpg",
      "/thread/5.jpg",
      "/thread/6.jpg",
      "/thread/7.jpg",
      "/thread/8.jpg",
      "/thread/9.jpg",
      "/thread/10.jpg",
      "/thread/11.jpg",
      "/thread/12.jpg"
    ],

    featuresdata:[
      "Users can sign up and log in securely.",
      "Create posts and manage their content easily.",
      "Update user profiles with personalized information.",
      "Follow and unfollow other users to curate a feed.",
      "Like and comment on posts to engage with content.",
      "View and manage all personal posts, including deletion.",
      "Explore other users' profiles to discover new connections.",
      "Responsive light and dark mode for personalized experience.",
      "Log out feature for secure session management.",
      "Built with MERN stack, Chakra UI, and Tailwind CSS for performance and designthread"
    ],
    link: "https://thread-clone-flame-mu.vercel.app/",
    code: "https://github.com/Shahmeer-09/Link",
  },
];
