import type { Metadata } from "next";
import "./globals.css";
import { RobotoSerif } from "./utils/fonts";
import LenisWrapper from "@/components/LenisWrapper";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RobotoSerif} antialiased   bg-zinc-100 `}>
        <LenisWrapper>{children}</LenisWrapper>
      </body>
    </html>
  );
}
